name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  # 每 12 小时执行一次
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist  # 
          keep_files: true  # 保留目标分支的现有文件
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
